name: Release VM

on:
  push:
  release:
    types:
      - created

jobs:
  release-vm:
    name: Release VM
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
          architecture: x64
      - 
        name: Build VM
        run: |-
          python util/vm/build.py -v -n -z xenial64server
